---
- name: "apt update"
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install python3 and python3-pip
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - python3
      - python3-pip