pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/sponkyy1/wordpress_task.git']]])
            }
        }
        
        stage('Execute Ansible') {
            steps {
                ansiblePlaybook credentialsId: '/home/ubuntu/.ssh/terraform', disableHostKeyChecking: true, installation: 'ansible', inventory: 'Jenkins/Ansible/hosts', playbook: 'Jenkins/Ansible/wordpress.yml'
            }
        }
    }
}