---
- name: "apt update"
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install software-properties-common
  apt:
    name: software-properties-common
    state: present
    update_cache: yes

- name: Add php stable repository from PPA and install its signing key on Ubuntu target
  ansible.builtin.apt_repository:
    repo: ppa:ondrej/php

- name: "apt update && apt upgrade"
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install php extensions
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - php7.4-fpm
      - php7.4-common
      - php7.4-mysql
      - php7.4-gmp
      - php7.4-curl
      - php7.4-intl
      - php7.4-mbstring
      - php7.4-xmlrpc
      - php7.4-gd
      - php7.4-xml
      - php7.4-cli
      - php7.4-zip