---
- name: "apt update && apt upgrade"
  apt:
    update_cache: yes
    cache_valid_time: 3600
  
- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Stop nginx.service  
  systemd:
    name: nginx.service
    state: stopped

- name: Start & Enable nginx.service  
  systemd:
    name: nginx.service
    state: started
    enabled: true

- name: Remove file default
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Remove file index.nginx-debian.html
  ansible.builtin.file:
    path: /var/www/html/index.nginx-debian.html
    state: absent

